package com.shortlet.config;

import com.shortlet.util.DatabaseUtil;
import com.shortlet.util.PasswordUtil;
import jakarta.servlet.ServletContextEvent;
import jakarta.servlet.ServletContextListener;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class AppStartupListener implements ServletContextListener {
    @Override
    public void contextInitialized(ServletContextEvent sce) {
        DatabaseUtil.init();
        try (Connection connection = DatabaseUtil.getConnection()) {
            createTables(connection);
            seedData(connection);
        } catch (SQLException e) {
            throw new IllegalStateException("Database startup failed", e);
        }
    }

    @Override
    public void contextDestroyed(ServletContextEvent sce) {
        DatabaseUtil.shutdown();
    }

    private void createTables(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(120) NOT NULL,
                        email VARCHAR(180) NOT NULL UNIQUE,
                        password_hash VARCHAR(500),
                        role VARCHAR(20) NOT NULL,
                        auth_provider VARCHAR(30) NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS properties (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(180) NOT NULL,
                        city VARCHAR(80) NOT NULL,
                        address VARCHAR(240) NOT NULL,
                        nightly_rate DECIMAL(12, 2) NOT NULL,
                        image_url VARCHAR(500),
                        source_url VARCHAR(500),
                        latitude DECIMAL(9, 6) DEFAULT 6.5244,
                        longitude DECIMAL(9, 6) DEFAULT 3.3792,
                        wifi BOOLEAN DEFAULT FALSE,
                        self_check_in BOOLEAN DEFAULT FALSE,
                        near_airport BOOLEAN DEFAULT FALSE,
                        reply_time_minutes INT DEFAULT 30,
                        rating DECIMAL(3, 2) DEFAULT 4.5
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS bookings (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        property_id BIGINT NOT NULL,
                        check_in DATE NOT NULL,
                        check_out DATE NOT NULL,
                        nights INT DEFAULT 1,
                        total_amount DECIMAL(12, 2) DEFAULT 0,
                        payment_method VARCHAR(40) DEFAULT 'PAY_ON_ARRIVAL',
                        payment_status VARCHAR(30) DEFAULT 'PENDING',
                        status VARCHAR(30) NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES users(id),
                        CONSTRAINT fk_booking_property FOREIGN KEY (property_id) REFERENCES properties(id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS property_images (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        property_id BIGINT NOT NULL,
                        image_url VARCHAR(500) NOT NULL,
                        CONSTRAINT fk_image_property FOREIGN KEY (property_id) REFERENCES properties(id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS wishlist (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        property_id BIGINT NOT NULL,
                        CONSTRAINT fk_wishlist_user FOREIGN KEY (user_id) REFERENCES users(id),
                        CONSTRAINT fk_wishlist_property FOREIGN KEY (property_id) REFERENCES properties(id),
                        CONSTRAINT uq_wishlist UNIQUE (user_id, property_id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS property_views (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        property_id BIGINT NOT NULL,
                        viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_view_property FOREIGN KEY (property_id) REFERENCES properties(id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS search_history (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        city VARCHAR(80) NOT NULL,
                        searched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_history_user FOREIGN KEY (user_id) REFERENCES users(id)
                    )
                    """);
            addColumnIfMissing(statement, "properties", "source_url", "VARCHAR(500)");
            addColumnIfMissing(statement, "properties", "latitude", "DECIMAL(9, 6) DEFAULT 6.5244");
            addColumnIfMissing(statement, "properties", "longitude", "DECIMAL(9, 6) DEFAULT 3.3792");
            addColumnIfMissing(statement, "properties", "wifi", "BOOLEAN DEFAULT FALSE");
            addColumnIfMissing(statement, "properties", "self_check_in", "BOOLEAN DEFAULT FALSE");
            addColumnIfMissing(statement, "properties", "near_airport", "BOOLEAN DEFAULT FALSE");
            addColumnIfMissing(statement, "properties", "reply_time_minutes", "INT DEFAULT 30");
            addColumnIfMissing(statement, "properties", "rating", "DECIMAL(3, 2) DEFAULT 4.5");
            addColumnIfMissing(statement, "bookings", "nights", "INT DEFAULT 1");
            addColumnIfMissing(statement, "bookings", "total_amount", "DECIMAL(12, 2) DEFAULT 0");
            addColumnIfMissing(statement, "bookings", "payment_method", "VARCHAR(40) DEFAULT 'PAY_ON_ARRIVAL'");
            addColumnIfMissing(statement, "bookings", "payment_status", "VARCHAR(30) DEFAULT 'PENDING'");
            addColumnIfMissing(statement, "bookings", "created_at", "TIMESTAMP DEFAULT CURRENT_TIMESTAMP");
            statement.execute("""
                    UPDATE bookings b
                    SET nights = DATEDIFF('DAY', b.check_in, b.check_out)
                    WHERE nights IS NULL OR nights <= 0
                    """);
            statement.execute("""
                    UPDATE bookings b
                    SET total_amount = (
                        SELECT p.nightly_rate * b.nights FROM properties p WHERE p.id = b.property_id
                    )
                    WHERE total_amount IS NULL OR total_amount = 0
                    """);
        }
    }

    private void seedData(Connection connection) throws SQLException {
        if (!hasRows(connection, "users")) {
            insertUser(connection, "Admin Manager", "admin@shortlet.com", "admin123", "ADMIN");
            insertUser(connection, "Ada Johnson", "ada@example.com", "password123", "USER");
            insertUser(connection, "Tunde Martins", "tunde@example.com", "password123", "USER");
            insertUser(connection, "Evans Dashboard", "evans@example.com", "password123", "USER");
        }

        // Seeding properties with coordinates, filters, and secondary image galleries!
        insertPropertyIfMissing(connection, "Luxury 2br in Ikeja With Pool and Gym", "Lagos", "Alausa, Ikeja, Lagos", "140000.00",
                "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
                "https://jiji.ng/lagos/temporary-and-vacation-rentals",
                6.6156, 3.3541, true, true, false, 45, 4.8,
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80",
                "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80");

        insertPropertyIfMissing(connection, "Luxury 3 Bedroom in Oniru VI", "Lagos", "Oniru, Victoria Island, Lagos", "250000.00",
                "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=80",
                "https://jiji.ng/lagos/temporary-and-vacation-rentals",
                6.4281, 3.4422, true, false, false, 15, 4.9,
                "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=900&q=80",
                "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=900&q=80");

        insertPropertyIfMissing(connection, "Fully Furnished 1 Bedroom Lagos Island", "Lagos", "Lagos Island, Lagos", "150000.00",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80",
                "https://jiji.ng/lagos-island-west/temporary-and-vacation-rentals",
                6.4549, 3.4246, true, true, true, 20, 4.6,
                "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
                "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=900&q=80");

        insertPropertyIfMissing(connection, "Exquisite 3 Bedroom Old Ikoyi", "Lagos", "Old Ikoyi, Lagos", "270000.00",
                "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80",
                "https://jiji.ng/lagos-island-west/temporary-and-vacation-rentals",
                6.4523, 3.4560, false, false, false, 120, 4.7,
                "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=80",
                "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=900&q=80");

        insertPropertyIfMissing(connection, "Luxury 2 Bedroom Wuse 2", "Abuja", "Wuse 2, Abuja", "160000.00",
                "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=900&q=80",
                "https://jiji.ng/abuja/temporary-and-vacation-rentals",
                9.0778, 7.4789, true, true, false, 30, 4.8,
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80",
                "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=900&q=80");

        insertPropertyIfMissing(connection, "Serviced Studio Katampe Extension", "Abuja", "Katampe Extension, Abuja", "90000.00",
                "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=900&q=80",
                "https://jiji.ng/katampe-extension/temporary-and-vacation-rentals/serviced-and-fully-furnished-studio-apartment-oOooWU41JINQpOG2B5RYUREw.html",
                9.1083, 7.4744, true, true, true, 5, 4.5,
                "https://images.unsplash.com/photo-1560448075-bb485b067938?auto=format&fit=crop&w=900&q=80",
                "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?auto=format&fit=crop&w=900&q=80");

        insertPropertyIfMissing(connection, "Jahi 2 Bedroom Shortlet", "Abuja", "Jahi Gilmore, Abuja", "90000.00",
                "https://images.unsplash.com/photo-1560448075-bb485b067938?auto=format&fit=crop&w=900&q=80",
                "https://jiji.ng/abuja/temporary-and-vacation-rentals",
                9.0889, 7.4339, true, false, false, 80, 4.4,
                "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
                "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80");

        insertPropertyIfMissing(connection, "Kubwa Affordable Apartment", "Abuja", "Kubwa, Abuja", "40000.00",
                "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=900&q=80",
                "https://jiji.ng/abuja/temporary-and-vacation-rentals",
                9.1606, 7.3242, false, true, false, 180, 4.2,
                "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?auto=format&fit=crop&w=900&q=80",
                "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=900&q=80");

        insertPropertyIfMissing(connection, "Quiet City Suite Bodija", "Ibadan", "Bodija, Ibadan", "75000.00",
                "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?auto=format&fit=crop&w=900&q=80",
                "https://jiji.ng/oyo/temporary-and-vacation-rentals",
                7.4292, 3.9056, true, true, false, 25, 4.7,
                "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=900&q=80",
                "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80");

        insertPropertyIfMissing(connection, "GRA Serviced Apartment", "Port Harcourt", "Old GRA, Port Harcourt", "85000.00",
                "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
                "https://jiji.ng/rivers/temporary-and-vacation-rentals",
                4.8156, 7.0498, true, false, true, 10, 4.6,
                "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=80",
                "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=900&q=80");

        insertPropertyIfMissing(connection, "Independence Layout Apartment", "Enugu", "Independence Layout, Enugu", "65000.00",
                "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=900&q=80",
                "https://jiji.ng/enugu/temporary-and-vacation-rentals",
                6.4381, 7.5116, true, true, false, 15, 4.5,
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80",
                "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80");

        insertPropertyIfMissing(connection, "Kano City Furnished Flat", "Kano", "Nassarawa GRA, Kano", "55000.00",
                "https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&w=900&q=80",
                "https://jiji.ng/kano/temporary-and-vacation-rentals",
                12.0022, 8.5919, true, true, true, 90, 4.3,
                "https://images.unsplash.com/photo-1560448075-bb485b067938?auto=format&fit=crop&w=900&q=80",
                "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=900&q=80");

        migrateLegacyPropertyData(connection);

        if (!hasRows(connection, "bookings")) {
            insertBooking(connection, 2, propertyId(connection, "Luxury 2br in Ikeja With Pool and Gym"), "2026-06-02", "2026-06-06", "CARD", "PAID", "CONFIRMED");
            insertBooking(connection, 2, propertyId(connection, "Luxury 3 Bedroom in Oniru VI"), "2026-07-12", "2026-07-15", "BANK_TRANSFER", "PENDING", "RESERVED");
            insertBooking(connection, 3, propertyId(connection, "Luxury 2 Bedroom Wuse 2"), "2026-06-20", "2026-06-24", "PAY_ON_ARRIVAL", "PENDING", "RESERVED");
        }
    }

    private void migrateLegacyPropertyData(Connection connection) throws SQLException {
        updateProperty(connection, "Skyline Studio", "Skyline Studio Ikeja", "Lagos", "Alausa, Ikeja, Lagos", "140000.00",
                "https://jiji.ng/lagos/temporary-and-vacation-rentals");
        updateProperty(connection, "Garden Loft", "Luxury 2 Bedroom Wuse 2", "Abuja", "Wuse 2, Abuja", "160000.00",
                "https://jiji.ng/abuja/temporary-and-vacation-rentals");
        updateProperty(connection, "Marina Apartment", "Luxury 3 Bedroom in Oniru VI", "Lagos", "Oniru, Victoria Island, Lagos", "250000.00",
                "https://jiji.ng/lagos/temporary-and-vacation-rentals");
        updateProperty(connection, "Quiet City Suite", "Quiet City Suite Bodija", "Ibadan", "Bodija, Ibadan", "75000.00",
                "https://jiji.ng/oyo/temporary-and-vacation-rentals");
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    UPDATE bookings b
                    SET total_amount = (
                        SELECT p.nightly_rate * b.nights FROM properties p WHERE p.id = b.property_id
                    )
                    """);
        }
    }

    private void updateProperty(Connection connection, String oldTitle, String newTitle, String city, String address, String nightlyRate, String sourceUrl) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "UPDATE properties SET title = ?, city = ?, address = ?, nightly_rate = ?, source_url = ? WHERE title = ?")) {
            statement.setString(1, newTitle);
            statement.setString(2, city);
            statement.setString(3, address);
            statement.setBigDecimal(4, new java.math.BigDecimal(nightlyRate));
            statement.setString(5, sourceUrl);
            statement.setString(6, oldTitle);
            statement.executeUpdate();
        }
    }

    private void addColumnIfMissing(Statement statement, String table, String column, String definition) throws SQLException {
        statement.execute("ALTER TABLE " + table + " ADD COLUMN IF NOT EXISTS " + column + " " + definition);
    }

    private boolean hasRows(Connection connection, String tableName) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("SELECT COUNT(*) FROM " + tableName);
             ResultSet rs = statement.executeQuery()) {
            rs.next();
            return rs.getInt(1) > 0;
        }
    }

    private void insertUser(Connection connection, String name, String email, String password, String role) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "INSERT INTO users(name, email, password_hash, role, auth_provider) VALUES (?, ?, ?, ?, 'LOCAL')")) {
            statement.setString(1, name);
            statement.setString(2, email);
            statement.setString(3, PasswordUtil.hash(password));
            statement.setString(4, role);
            statement.executeUpdate();
        }
    }

    private void insertPropertyIfMissing(Connection connection, String title, String city, String address, String nightlyRate, String imageUrl, String sourceUrl,
                                         double latitude, double longitude, boolean wifi, boolean selfCheckIn, boolean nearAirport, int replyTimeMinutes, double rating, String... secondaryImages) throws SQLException {
        long propertyId = 0;
        try (PreparedStatement check = connection.prepareStatement("SELECT id FROM properties WHERE title = ?")) {
            check.setString(1, title);
            try (ResultSet rs = check.executeQuery()) {
                if (rs.next()) {
                    propertyId = rs.getLong("id");
                }
            }
        }
        if (propertyId == 0) {
            try (PreparedStatement statement = connection.prepareStatement(
                    """
                    INSERT INTO properties(title, city, address, nightly_rate, image_url, source_url, latitude, longitude, wifi, self_check_in, near_airport, reply_time_minutes, rating)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """, Statement.RETURN_GENERATED_KEYS)) {
                statement.setString(1, title);
                statement.setString(2, city);
                statement.setString(3, address);
                statement.setBigDecimal(4, new java.math.BigDecimal(nightlyRate));
                statement.setString(5, imageUrl);
                statement.setString(6, sourceUrl);
                statement.setDouble(7, latitude);
                statement.setDouble(8, longitude);
                statement.setBoolean(9, wifi);
                statement.setBoolean(10, selfCheckIn);
                statement.setBoolean(11, nearAirport);
                statement.setInt(12, replyTimeMinutes);
                statement.setDouble(13, rating);
                statement.executeUpdate();
                try (ResultSet keys = statement.getGeneratedKeys()) {
                    if (keys.next()) {
                        propertyId = keys.getLong(1);
                    }
                }
            }
        }
        
        // Seed secondary images for this property
        if (propertyId > 0) {
            // First, delete any existing images to make seeding idempotent and clean
            try (PreparedStatement deleteImg = connection.prepareStatement("DELETE FROM property_images WHERE property_id = ?")) {
                deleteImg.setLong(1, propertyId);
                deleteImg.executeUpdate();
            }
            
            // Insert primary image
            try (PreparedStatement insertImg = connection.prepareStatement("INSERT INTO property_images(property_id, image_url) VALUES (?, ?)")) {
                insertImg.setLong(1, propertyId);
                insertImg.setString(2, imageUrl);
                insertImg.executeUpdate();
                
                for (String secImg : secondaryImages) {
                    insertImg.setLong(1, propertyId);
                    insertImg.setString(2, secImg);
                    insertImg.executeUpdate();
                }
            }
        }
    }

    private long propertyId(Connection connection, String title) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("SELECT id FROM properties WHERE title = ?")) {
            statement.setString(1, title);
            try (ResultSet rs = statement.executeQuery()) {
                if (!rs.next()) {
                    throw new SQLException("Missing seeded property: " + title);
                }
                return rs.getLong("id");
            }
        }
    }

    private void insertBooking(Connection connection, long userId, long propertyId, String checkIn, String checkOut,
                               String paymentMethod, String paymentStatus, String status) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                """
                        INSERT INTO bookings(user_id, property_id, check_in, check_out, nights, total_amount, payment_method, payment_status, status)
                        SELECT ?, ?, ?, ?, DATEDIFF('DAY', CAST(? AS DATE), CAST(? AS DATE)), p.nightly_rate * DATEDIFF('DAY', CAST(? AS DATE), CAST(? AS DATE)), ?, ?, ?
                        FROM properties p WHERE p.id = ?
                        """)) {
            statement.setLong(1, userId);
            statement.setLong(2, propertyId);
            statement.setDate(3, java.sql.Date.valueOf(checkIn));
            statement.setDate(4, java.sql.Date.valueOf(checkOut));
            statement.setString(5, checkIn);
            statement.setString(6, checkOut);
            statement.setString(7, checkIn);
            statement.setString(8, checkOut);
            statement.setString(9, paymentMethod);
            statement.setString(10, paymentStatus);
            statement.setString(11, status);
            statement.setLong(12, propertyId);
            statement.executeUpdate();
        }
    }
}
