package com.shortlet.config;

import com.shortlet.util.DatabaseUtil;
import com.shortlet.util.PasswordUtil;
import jakarta.servlet.ServletContextEvent;
import jakarta.servlet.ServletContextListener;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class AppStartupListener implements ServletContextListener {
    @Override
    public void contextInitialized(ServletContextEvent sce) {
        DatabaseUtil.init();
        try (Connection connection = DatabaseUtil.getConnection()) {
            createTables(connection);
            seedData(connection);
        } catch (SQLException e) {
            throw new IllegalStateException("Database startup failed", e);
        }
    }

    @Override
    public void contextDestroyed(ServletContextEvent sce) {
        DatabaseUtil.shutdown();
    }

    private void createTables(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(120) NOT NULL,
                        email VARCHAR(180) NOT NULL UNIQUE,
                        password_hash VARCHAR(500),
                        role VARCHAR(20) NOT NULL,
                        auth_provider VARCHAR(30) NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS properties (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(180) NOT NULL,
                        city VARCHAR(80) NOT NULL,
                        address VARCHAR(240) NOT NULL,
                        nightly_rate DECIMAL(12, 2) NOT NULL,
                        image_url VARCHAR(500)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS bookings (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        property_id BIGINT NOT NULL,
                        check_in DATE NOT NULL,
                        check_out DATE NOT NULL,
                        status VARCHAR(30) NOT NULL,
                        CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES users(id),
                        CONSTRAINT fk_booking_property FOREIGN KEY (property_id) REFERENCES properties(id)
                    )
                    """);
        }
    }

    private void seedData(Connection connection) throws SQLException {
        if (hasRows(connection, "users")) {
            return;
        }
        insertUser(connection, "Admin Manager", "admin@shortlet.com", "admin123", "ADMIN");
        insertUser(connection, "Ada Johnson", "ada@example.com", "password123", "USER");
        insertUser(connection, "Tunde Martins", "tunde@example.com", "password123", "USER");

        insertProperty(connection, "Skyline Studio", "Lagos", "Victoria Island, Lagos", "115.00",
                "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80");
        insertProperty(connection, "Garden Loft", "Abuja", "Maitama, Abuja", "145.00",
                "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80");
        insertProperty(connection, "Marina Apartment", "Lagos", "Lekki Phase 1, Lagos", "180.00",
                "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=80");
        insertProperty(connection, "Quiet City Suite", "Ibadan", "Bodija, Ibadan", "75.00",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80");

        insertBooking(connection, 2, 1, "2026-06-02", "2026-06-06", "CONFIRMED");
        insertBooking(connection, 2, 3, "2026-07-12", "2026-07-15", "PENDING");
        insertBooking(connection, 3, 2, "2026-06-20", "2026-06-24", "CONFIRMED");
    }

    private boolean hasRows(Connection connection, String tableName) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("SELECT COUNT(*) FROM " + tableName);
             ResultSet rs = statement.executeQuery()) {
            rs.next();
            return rs.getInt(1) > 0;
        }
    }

    private void insertUser(Connection connection, String name, String email, String password, String role) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "INSERT INTO users(name, email, password_hash, role, auth_provider) VALUES (?, ?, ?, ?, 'LOCAL')")) {
            statement.setString(1, name);
            statement.setString(2, email);
            statement.setString(3, PasswordUtil.hash(password));
            statement.setString(4, role);
            statement.executeUpdate();
        }
    }

    private void insertProperty(Connection connection, String title, String city, String address, String nightlyRate, String imageUrl) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "INSERT INTO properties(title, city, address, nightly_rate, image_url) VALUES (?, ?, ?, ?, ?)")) {
            statement.setString(1, title);
            statement.setString(2, city);
            statement.setString(3, address);
            statement.setBigDecimal(4, new java.math.BigDecimal(nightlyRate));
            statement.setString(5, imageUrl);
            statement.executeUpdate();
        }
    }

    private void insertBooking(Connection connection, long userId, long propertyId, String checkIn, String checkOut, String status) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "INSERT INTO bookings(user_id, property_id, check_in, check_out, status) VALUES (?, ?, ?, ?, ?)")) {
            statement.setLong(1, userId);
            statement.setLong(2, propertyId);
            statement.setDate(3, java.sql.Date.valueOf(checkIn));
            statement.setDate(4, java.sql.Date.valueOf(checkOut));
            statement.setString(5, status);
            statement.executeUpdate();
        }
    }
}
